port: 8000

db: 
  username: "postgres"
  host: "localhost"
  port: 5434
  dbname: "todo-db"
  sslmode: "disable"

logger:
  level: debug
  format: pretty

# logger:
#   level: warn
#   format: json

jwt:
  ttl: 12h

bcrypt:
  cost: 10